name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}  # Ensure this is set correctly
          password: ${{ secrets.DOCKER_PASSWORD }}  # Ensure this is set correctly

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.DOCKER_USERNAME }}/jscarmods-fivem:latest  # Ensure this is the correct image name
          context: .  # Set the context to the current directory
          file: ../Dockerfile  # Specify the path to your Dockerfile if it's not in the root
